//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SECRETLABS_NETMF_HARDWARE_H_
#define _SECRETLABS_NETMF_HARDWARE_H_

#include <TinyCLR_Interop.h>
struct Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_AnalogInput
{
    static const int FIELD___disposed = 1;
    static const int FIELD___pin = 2;
    static const int FIELD___minValue = 3;
    static const int FIELD___maxValue = 4;

    TINYCLR_NATIVE_DECLARE(ADC_Enable___VOID__U4);
    TINYCLR_NATIVE_DECLARE(ADC_Disable___VOID__U4);
    TINYCLR_NATIVE_DECLARE(ADC_Read___U4__U4);

    //--//

};

struct Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_PWM
{
    static const int FIELD___disposed = 1;
    static const int FIELD___pin = 2;

    TINYCLR_NATIVE_DECLARE(PWM_Enable___VOID__U4);
    TINYCLR_NATIVE_DECLARE(PWM_Disable___VOID__U4);
    TINYCLR_NATIVE_DECLARE(PWM_SetDutyCycle___VOID__U4__U4);
    TINYCLR_NATIVE_DECLARE(PWM_SetPulse___VOID__U4__U4__U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SecretLabs_NETMF_Hardware;

#endif  //_SECRETLABS_NETMF_HARDWARE_H_
