//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SecretLabs_NETMF_Hardware.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_AnalogInput::ADC_Enable___VOID__U4,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_AnalogInput::ADC_Disable___VOID__U4,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_AnalogInput::ADC_Read___U4__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_PWM::PWM_Enable___VOID__U4,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_PWM::PWM_Disable___VOID__U4,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_PWM::PWM_SetDutyCycle___VOID__U4__U4,
    Library_SecretLabs_NETMF_Hardware_SecretLabs_NETMF_Hardware_PWM::PWM_SetPulse___VOID__U4__U4__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SecretLabs_NETMF_Hardware =
{
    "SecretLabs.NETMF.Hardware", 
    0xA99F07CD,
    method_lookup
};

